tasks:
  install-brew:
    context: bash
    command:
      - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh

  install-alacritty:
    context: brew
    command: install alacritty

contexts:

  bash:
    executable:
      bin: /bin/bash
    before: echo -n "using bash as context for taskctl..."
  brew:
    executable:
      bin: brew
      args: ["install"]
    before: echo -n "using brew package manager for taskctl..."
