tasks:
  install-brew:
    context: bash
    command:
      - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh

  brew-install:
    context: brew
    command: ${ARGS}

contexts:

  bash:
    executable:
      bin: /bin/bash
      args:
        - -c
    before: echo "using bash as context for taskctl..."

  brew:
    executable:
      bin: brew
      args: ["install"]
    before: echo -n "using brew package manager for taskctl..."